name: StrawberryChat
version: '2.1.0'
main: dev.curseforged.strawberryChat.StrawberryChat
api-version: '1.21.11'
authors: [ cursefroge ]
description: Custom chat plugin for The Strawberry Farm
bootstrapper: dev.curseforged.strawberryChat.StrawberryChatBootstrap
permissions:
  strawberrychat.velocity:
    description: Allows using /velocity to apply velocity to players
    default: op
  strawberrychat.crash:
    description: Allows using /crash to attempt to crash specified players' clients
    default: op
  strawberrychat.demo:
    description: Allows using /demo to show the demo screen to specified players
    default: op
  strawberrychat.credits:
    description: Allows using /credits to show the end credit screen to specified players
    default: op
  strawberrychat.skull:
    description: Allows using /skull to give the player a custom skull
    default: op
  strawberrychat.world:
    description: Allows using /world to change the player's world
    default: op
  strawberrychat.allow-gamemode-change:
    description: Allows using the gamemode switcher
    default: op
